version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: Todo_Db_Local
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: springboot-app
    restart: always  # ✅ Automatically restart if connection fails
    depends_on:
      mysql:
        condition: service_healthy  # ✅ Wait for MySQL to be healthy
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  mysql_data:
